require:
  - standard

plugins:
  - standard-custom
  - standard-performance
  - rubocop-performance
  - rubocop-rails
  - rubocop-minitest

inherit_gem:
  standard: config/base.yml
  standard-custom: config/base.yml
  standard-performance: config/base.yml
  rubocop-rails: config/default.yml
  rubocop-minitest: config/default.yml

AllCops:
  TargetRubyVersion: 3.4
