require:
  - standard/cop/block_single_line_braces
  - rubocop-rails
  - rubocop-minitest

inherit_gem:
  standard: config/base.yml
  rubocop-rails: config/default.yml
  rubocop-minitest: config/default.yml

AllCops:
  TargetRubyVersion: 3.4
